sample:	sample.cpp planet.cpp planet.h
	g++ -g -o run planet.cpp sample.cpp -lglut -lGL  -lGLU


planets: planet.cpp testing_driver.cpp planet.h
	g++ -g -Wall planet.cpp testing_driver.cpp -o planets
